version: '3'
services:
  recorder:
    container_name: meteor-ip-cam-recorder
    image: boonya/meteor-ip-cam-recorder:latest
    depends_on:
      - mongo
    network_mode: host
    volumes:
      - /media/Recorder/:/media/Recorder/:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
     - .env.recorder
    environment:
      NODE_ENV: development
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/:ro
      - mongo-configdb:/data/configdb
      - mongo-db:/data/db
    env_file:
     - .env.mongo
    restart: unless-stopped

volumes:
  mongo-configdb:
  mongo-db:
