version: '3'

services:
  recorder:
    container_name: meteor-recorder
    image: boonya/meteor-recorder:test
    networks:
      - db
    privileged: true
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - $HOME/Movies/recorder:/mnt:rw
    env_file:
      - .env.recorder
    restart: unless-stopped

  mongo:
    container_name: meteor-recorder-mongo
    image: mongo:4.4.10
    networks:
      - db
    ports:
      - 27017:27017
    volumes:
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/:ro
      - mongo-configdb:/data/configdb
      - mongo-db:/data/db
    env_file:
      - .env.mongo
    restart: unless-stopped

volumes:
  mongo-configdb:
  mongo-db:


networks:
  db:
    name: meteor-recorder
