version: '3'
services:
  recorder:
    container_name: meteor-recorder
    image: boonya/meteor-recorder:next
    privileged: true
    depends_on:
      - mongo
    # network_mode: host
    ports:
      - 3000:3000
    volumes:
      # - /media/Recorder/:/media/Recorder/:rw
      - $HOME/Movies/recorder/:/media/Recorder/:rw
      # - /etc/localtime:/etc/localtime:ro
    env_file:
     - .env.recorder
    environment:
      NODE_ENV: development
    restart: unless-stopped

  mongo:
    container_name: meteor-recorder-mongo
    image: mongo:4.4.10
    ports:
      - 27017:27017
    volumes:
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/:ro
      - mongo-configdb:/data/configdb
      - mongo-db:/data/db
      # - /etc/localtime:/etc/localtime:ro
    env_file:
     - .env.mongo
    restart: unless-stopped

volumes:
  mongo-configdb:
  mongo-db:
