import ENV from './env';

export const RECORDER = {
	FOLDER: ENV.RECORDER_FOLDER,
	SEGMENT_TIME: ENV.RECORDER_SEGMENT_TIME || undefined,
	DIR_SIZE_THRESHOLD: ENV.RECORDER_DIR_SIZE_THRESHOLD || undefined,
	AUTO_CLEAR: ENV.RECORDER_AUTO_CLEAR === 'true',
};
