import {
	RECORDER_FOLDER,
	RECORDER_SEGMENT_TIME,
	RECORDER_DIR_SIZE_THRESHOLD,
	SHOW_LOGS,
	SHOW_PROGRESS,
} from './env';

export const RECORDER = {
	FOLDER: RECORDER_FOLDER,
	SEGMENT_TIME: RECORDER_SEGMENT_TIME || undefined,
	DIR_SIZE_THRESHOLD: RECORDER_DIR_SIZE_THRESHOLD || undefined,
};

export const ENV = {
	SHOW_LOGS: SHOW_LOGS === 'true',
	SHOW_PROGRESS: SHOW_PROGRESS === 'true',
};
