import {
	RECORDER_FOLDER,
	RECORDER_SEGMENT_TIME,
	RECORDER_DIR_SIZE_THRESHOLD,
	RECORDER_AUTO_CLEAR,
	LOGGING,
} from './env';

export const RECORDER = {
	FOLDER: RECORDER_FOLDER,
	SEGMENT_TIME: RECORDER_SEGMENT_TIME || undefined,
	DIR_SIZE_THRESHOLD: RECORDER_DIR_SIZE_THRESHOLD || undefined,
	AUTO_CLEAR: RECORDER_AUTO_CLEAR === 'true',
};

export const ENV = {
	LOGGING: LOGGING === 'true',
}
