name: "Meteor Bundle and Docker Image"

on:
  push:
  release:
    types: [published]

env:
  DOCKER_HUB_IMAGE: "hub.docker.com/${{ github.repository }}"
  GHCR_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  bundle:
    name: Build Meteor bundle 📦
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - id: definitions
        run: |
          METEOR=$(cat .meteor/release | awk -F'@' '{print $2}')
          echo ::set-output name=meteor::${METEOR}

          VERSION=$(cat package.json | jq -r '.version')
          echo ::set-output name=version::${VERSION}

          HASH="${GITHUB_SHA}"
          echo ::set-output name=tag::${HASH}

          BUNDLE=${{ github.event.repository.name }}-${HASH}.tar.gz
          echo ::set-output name=bundle::${BUNDLE}

          META=$( jq -n \
            --arg meteor ${METEOR} \
            --arg version ${VERSION} \
            --arg hash ${HASH} \
            --arg bundle ${BUNDLE} \
            '{"meteor": $meteor, "version": $version, "hash": $hash, "bundle": $bundle}'
          )
          echo ${META} > meta.json

      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ steps.definitions.outputs.meteor }}

      - run: meteor npm install
      - run: meteor build .
      - name: Rename bundle
        run: |
          mv ${{ github.event.repository.name }}.tar.gz ${{ steps.definitions.outputs.bundle }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            meta.json
            ${{ steps.definitions.outputs.bundle }}
            .dockerignore
            Dockerfile
            docker-compose.yaml
            .env.mongo.template
            .env.recorder.template
            meteor-recorder.service
            README.md
            LICENSE
          if-no-files-found: error

  docker:
    name: Build Docker Image 🐳
    runs-on: ubuntu-20.04
    needs: [bundle]
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Define metadata
        id: meta
        run: |
          ls -alh .

          VERSION=$(cat meta.json | jq -r '.version')
          echo ::set-output name=version::${VERSION}

          HASH=$(cat meta.json | jq -r '.hash')
          echo ::set-output name=hash::${HASH}

          BUNDLE=$(cat meta.json | jq -r '.bundle')
          echo ::set-output name=bundle::${BUNDLE}

          TAGS="${GHCR_IMAGE}:${HASH},${GHCR_IMAGE}:${{ github.event.ref }}"
          if [[ $GITHUB_REF == ref/head/main ]]; then
            TAGS="${TAGS},${DOCKER_HUB_IMAGE}:${VERSION},${DOCKER_HUB_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}

          echo "bundle name: ${BUNDLE}"
          echo "hash: ${HASH}"
          echo "version: ${VERSION}"
          echo "tags: ${TAGS}"

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BUNDLE=${{ steps.meta.outputs.bundle }}
