name: "Meteor Bundle and Docker Image"

on:
  push:
  release:
    types: [published]

env:
  DOCKER_HUB_IMAGE: "hub.docker.com/${{ github.repository }}"

jobs:
  bundle:
    name: Build Meteor bundle 📦
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - id: definitions
        run: |
          METEOR=$(cat .meteor/release | awk -F'@' '{print $2}')
          echo ::set-output name=meteor::${METEOR}

          VERSION=$(cat package.json | jq -r '.version')
          echo ::set-output name=version::${VERSION}

          TAG="${GITHUB_SHA}"
          echo ::set-output name=tag::${TAG}

          BUNDLE=${{ github.event.repository.name }}-${TAG}.tar.gz
          echo ::set-output name=bundle::${BUNDLE}

      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ steps.definitions.outputs.meteor }}

      - run: meteor npm install
      - run: meteor build .
      - name: Rename bundle
        run: |
          mv ${{ github.event.repository.name }}.tar.gz ${{ steps.definitions.outputs.bundle }}
      - name: Create version file
        run: |
          echo ${{ steps.definitions.outputs.version }} > version.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            version.txt
            ${{ steps.definitions.outputs.bundle }}
            .dockerignore
            Dockerfile
            docker-compose.yaml
            .env.mongo.template
            .env.recorder.template
            meteor-recorder.service
            README.md
            LICENSE
          if-no-files-found: error

  docker:
    name: Build Docker Image 🐳
    runs-on: ubuntu-20.04
    needs: [bundle]
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Define metadata
        id: meta
        run: |
          ls -alh .

          BUNDLE=$(ls meteor-recorder-*.tar.gz)
          echo ::set-output name=bundle::${BUNDLE}

          HASH=$(echo ${BUNDLE} | sed -nE 's/^meteor\-recorder\-(.+)\.tar\.gz$/\1/p')
          echo ::set-output name=hash::${HASH}

          VERSION=$(cat version.txt)
          echo ::set-output name=version::${VERSION}

          TAGS="${DOCKER_HUB_IMAGE}:${GITHUB_SHA}"
          if [[ $GITHUB_REF == ref/head/main ]]; then
            TAGS="${TAGS},${DOCKER_HUB_IMAGE}:latest"
          fi

          echo "bundle name: ${BUNDLE}"
          echo "hash: ${HASH}"
          echo "version: ${VERSION}"
          echo "tags: ${TAGS}"

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BUNDLE=${{ steps.meta.outputs.bundle }}
