name: "Release 🚀"

on:
  release:
    types: [published]

env:
  GHCR_IMAGE: "ghcr.io/${{ github.repository }}"
  DOCKER_HUB_IMAGE: "${{ github.repository }}"

jobs:
  version:
    name: Compare tag and package version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "Check"
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          if [[ ${GITHUB_REF_NAME} !=  ${VERSION} ]];
          then
            echo "Tag (${GITHUB_REF_NAME}) and package version (${VERSION}) are different."
            echo "Something went wrong."
            exit 1
          fi

  verify:
    needs: [version]
    uses: ./.github/workflows/verify.yml

  build:
    needs: [verify, version]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    name: Copy Images from GHCR to DockerHub
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN_RW }}

      - name: Prepare source and targets
        id: meta
        run: |
          SRC="${{ env.GHCR_IMAGE }}:${GITHUB_REF_NAME}"
          echo ::set-output name=src::${SRC}
          DST="${{ env.GHCR_IMAGE }}:${GITHUB_REF_NAME},${{ env.GHCR_IMAGE }}:latest,${{ env.DOCKER_HUB_IMAGE }}:${GITHUB_REF_NAME},${{ env.DOCKER_HUB_IMAGE }}:latest"
          echo ::set-output name=dst::${DST}

      - name: Push Image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ steps.meta.outputs.src }}
          dst: ${{ steps.meta.outputs.dst }}
