name: "Release 🚀"

on:
  release:
    types: [published]

env:
  GHCR_IMAGE: "ghcr.io/${{ github.repository }}"
  DOCKER_HUB_IMAGE: "${{ github.repository }}"

jobs:
  release:
    name: Copy Images from GHCR to DockerHub
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN_RW }}

      - name: Push Image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: "${{ env.GHCR_IMAGE }}:${GITHUB_REF_NAME}"
          dst: |
            "${{ env.DOCKER_HUB_IMAGE }}:latest"
            "${{ env.DOCKER_HUB_IMAGE }}:${GITHUB_REF_NAME}"
            "${{ env.GHCR_IMAGE }}:latest"
