name: "[Test] Build and release meteor bundle 📦 and Docker Image 🐳"

on: [push]

jobs:
  build:
    name: Build JavaScript bundle 📦
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Define versions
        id: versions
        run: |
          BUNDLE=$(cat package.json | jq -r '.version')
          METEOR=$(cat .meteor/release | awk -F'@' '{print $2}')

          echo ::set-output name=bundle::${BUNDLE}
          echo ::set-output name=meteor::${METEOR}

      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ steps.versions.outputs.meteor }}

      - run: meteor npm install
      - run: meteor build .
      - name: Rename bundle
        id: bundle
        run: |
          NAME=${{ github.event.repository.name }}-${{ steps.versions.outputs.bundle }}.tar.gz
          echo ::set-output name=name::${NAME}
          mv ${{ github.event.repository.name }}.tar.gz ${NAME}
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ${{ steps.bundle.outputs.name }}
            .dockerignore
            Dockerfile
            docker-compose.yaml
            .env.mongo.template
            .env.recorder.template
            meteor-recorder.service
            README.md
            LICENSE
          if-no-files-found: error
