name: "Test workflow"

on:
  push:
    tags:
      - workflow-*
    branches:
      - workflow-*

env:
  GHCR_IMAGE: "ghcr.io/${{ github.repository }}"
  DOCKER_HUB_IMAGE: "${{ github.repository }}"

jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - name: Define metadata
        id: meta
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          if [[ ${GITHUB_REF} =~ ^refs/tags/ ]];
          then
            echo "Tag pushed"
          else
            echo "Head pushed"
          fi

  reusable_workflow_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build

  release:
    name: Copy Images from GHCR to DockerHub
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN_RW }}

      - name: Push Image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: "${{ env.GHCR_IMAGE }}:${GITHUB_REF_NAME}"
          dst: |
            "${{ env.DOCKER_HUB_IMAGE }}:my-test"
            "${{ env.DOCKER_HUB_IMAGE }}:${GITHUB_REF_NAME}"
            "${{ env.GHCR_IMAGE }}:my-test"
