name: "Verification 👮🏽‍♂️"

on:
  workflow_call:
  push:
    tags-ignore: ["*"]
    paths-ignore: ["**.md", "LICENSE"]
    branches: [main]
  pull_request:
    paths-ignore: ["**.md", "LICENSE"]

jobs:
  versions:
    name: Versions
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Define metadata
        id: meta
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          METEOR=$(cat .meteor/release | awk -F'@' '{print $2}')
          NVMRC=$(cat .nvmrc)
          NODE=$(cat package.json | jq -r '.engines.node')
          NPM=$(cat package.json | jq -r '.engines.npm')

          echo ::set-output name=version::${VERSION}
          echo ::set-output name=meteor::${METEOR}
          echo ::set-output name=nvmrc::${NVMRC}
          echo ::set-output name=node::${NODE}
          echo ::set-output name=npm::${NPM}

          echo "bundle version is: ${VERSION}"
          echo "meteor version is: ${METEOR}"
          echo ".nvmrc version is: ${NVMRC}"
          echo "node version is: ${NODE}"
          echo "npm version is: ${NPM}"

      - name: Verify required node version
        run: |
          if [ ${{ steps.meta.outputs.nvmrc }} == ${{ steps.meta.outputs.node }} ];
          then
            echo "Node versions are same"
          else
            echo "Node version different in .nvmrc file and package.json"
            exit 1
          fi

      - name: Verify package version
        run: |
          if [[ ${{ steps.meta.outputs.version }} =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]];
          then
            echo "Package version string is valid"
          else
            echo "Package version string is not valid. See: https://docs.npmjs.com/about-semantic-versioning"
            exit 1
          fi

  lint:
    name: Linting 🔎
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint

  test:
    name: Test Jest 🧪
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run test

  test-meteor:
    name: Test Meteor 🧪
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Define meteor version
        id: versions
        run: |
          METEOR=$(cat .meteor/release | awk -F'@' '{print $2}')
          echo ::set-output name=meteor::${METEOR}
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: "${{ steps.meta.outputs.meteor }}"
      - run: meteor npm install
      - run: npm run test:meteor
